/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
	v1alpha1 "plenus.io/plenuslb/pkg/apis/loadbalancing/v1alpha1"
)

// PersistentIPPoolLister helps list PersistentIPPools.
type PersistentIPPoolLister interface {
	// List lists all PersistentIPPools in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.PersistentIPPool, err error)
	// Get retrieves the PersistentIPPool from the index for a given name.
	Get(name string) (*v1alpha1.PersistentIPPool, error)
	PersistentIPPoolListerExpansion
}

// persistentIPPoolLister implements the PersistentIPPoolLister interface.
type persistentIPPoolLister struct {
	indexer cache.Indexer
}

// NewPersistentIPPoolLister returns a new PersistentIPPoolLister.
func NewPersistentIPPoolLister(indexer cache.Indexer) PersistentIPPoolLister {
	return &persistentIPPoolLister{indexer: indexer}
}

// List lists all PersistentIPPools in the indexer.
func (s *persistentIPPoolLister) List(selector labels.Selector) (ret []*v1alpha1.PersistentIPPool, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.PersistentIPPool))
	})
	return ret, err
}

// Get retrieves the PersistentIPPool from the index for a given name.
func (s *persistentIPPoolLister) Get(name string) (*v1alpha1.PersistentIPPool, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("persistentippool"), name)
	}
	return obj.(*v1alpha1.PersistentIPPool), nil
}
