/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "plenus.io/plenuslb/pkg/apis/loadbalancing/v1alpha1"
)

// FakeIPAllocations implements IPAllocationInterface
type FakeIPAllocations struct {
	Fake *FakeLoadbalancingV1alpha1
	ns   string
}

var ipallocationsResource = schema.GroupVersionResource{Group: "loadbalancing.plenus.io", Version: "v1alpha1", Resource: "ipallocations"}

var ipallocationsKind = schema.GroupVersionKind{Group: "loadbalancing.plenus.io", Version: "v1alpha1", Kind: "IPAllocation"}

// Get takes name of the iPAllocation, and returns the corresponding iPAllocation object, and an error if there is any.
func (c *FakeIPAllocations) Get(name string, options v1.GetOptions) (result *v1alpha1.IPAllocation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(ipallocationsResource, c.ns, name), &v1alpha1.IPAllocation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IPAllocation), err
}

// List takes label and field selectors, and returns the list of IPAllocations that match those selectors.
func (c *FakeIPAllocations) List(opts v1.ListOptions) (result *v1alpha1.IPAllocationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(ipallocationsResource, ipallocationsKind, c.ns, opts), &v1alpha1.IPAllocationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.IPAllocationList{ListMeta: obj.(*v1alpha1.IPAllocationList).ListMeta}
	for _, item := range obj.(*v1alpha1.IPAllocationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested iPAllocations.
func (c *FakeIPAllocations) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(ipallocationsResource, c.ns, opts))

}

// Create takes the representation of a iPAllocation and creates it.  Returns the server's representation of the iPAllocation, and an error, if there is any.
func (c *FakeIPAllocations) Create(iPAllocation *v1alpha1.IPAllocation) (result *v1alpha1.IPAllocation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(ipallocationsResource, c.ns, iPAllocation), &v1alpha1.IPAllocation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IPAllocation), err
}

// Update takes the representation of a iPAllocation and updates it. Returns the server's representation of the iPAllocation, and an error, if there is any.
func (c *FakeIPAllocations) Update(iPAllocation *v1alpha1.IPAllocation) (result *v1alpha1.IPAllocation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(ipallocationsResource, c.ns, iPAllocation), &v1alpha1.IPAllocation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IPAllocation), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeIPAllocations) UpdateStatus(iPAllocation *v1alpha1.IPAllocation) (*v1alpha1.IPAllocation, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(ipallocationsResource, "status", c.ns, iPAllocation), &v1alpha1.IPAllocation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IPAllocation), err
}

// Delete takes name of the iPAllocation and deletes it. Returns an error if one occurs.
func (c *FakeIPAllocations) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(ipallocationsResource, c.ns, name), &v1alpha1.IPAllocation{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIPAllocations) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(ipallocationsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.IPAllocationList{})
	return err
}

// Patch applies the patch and returns the patched iPAllocation.
func (c *FakeIPAllocations) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.IPAllocation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(ipallocationsResource, c.ns, name, pt, data, subresources...), &v1alpha1.IPAllocation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IPAllocation), err
}
