# hello-kubernetes.yaml

apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: hello-kubernetes
---
apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes2
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  externalIPs:
    - 22.33.44.55
  selector:
    app: hello-kubernetes
---
apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes3
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  externalIPs:
    - 22.33.44.56
    - 22.33.44.57
    - 22.33.44.58
  selector:
    app: hello-kubernetes
---
apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes4
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: "default"
    targetPort: 8080
  - port: 8080
    name: "second"
    targetPort: 8080
  selector:
    app: hello-kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-kubernetes
  template:
    metadata:
      labels:
        app: hello-kubernetes
    spec:
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.5
        ports:
        - containerPort: 8080
