/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	loadbalancingv1alpha1 "plenus.io/plenuslb/pkg/apis/loadbalancing/v1alpha1"
	versioned "plenus.io/plenuslb/pkg/client/clientset/versioned"
	internalinterfaces "plenus.io/plenuslb/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "plenus.io/plenuslb/pkg/client/listers/loadbalancing/v1alpha1"
)

// EphemeralIPPoolInformer provides access to a shared informer and lister for
// EphemeralIPPools.
type EphemeralIPPoolInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.EphemeralIPPoolLister
}

type ephemeralIPPoolInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewEphemeralIPPoolInformer constructs a new informer for EphemeralIPPool type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewEphemeralIPPoolInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredEphemeralIPPoolInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredEphemeralIPPoolInformer constructs a new informer for EphemeralIPPool type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredEphemeralIPPoolInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.LoadbalancingV1alpha1().EphemeralIPPools().List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.LoadbalancingV1alpha1().EphemeralIPPools().Watch(options)
			},
		},
		&loadbalancingv1alpha1.EphemeralIPPool{},
		resyncPeriod,
		indexers,
	)
}

func (f *ephemeralIPPoolInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredEphemeralIPPoolInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *ephemeralIPPoolInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&loadbalancingv1alpha1.EphemeralIPPool{}, f.defaultInformer)
}

func (f *ephemeralIPPoolInformer) Lister() v1alpha1.EphemeralIPPoolLister {
	return v1alpha1.NewEphemeralIPPoolLister(f.Informer().GetIndexer())
}
