/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	loadbalancingv1alpha1 "plenus.io/plenuslb/pkg/apis/loadbalancing/v1alpha1"
	versioned "plenus.io/plenuslb/pkg/client/clientset/versioned"
	internalinterfaces "plenus.io/plenuslb/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "plenus.io/plenuslb/pkg/client/listers/loadbalancing/v1alpha1"
)

// IPAllocationInformer provides access to a shared informer and lister for
// IPAllocations.
type IPAllocationInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.IPAllocationLister
}

type iPAllocationInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewIPAllocationInformer constructs a new informer for IPAllocation type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewIPAllocationInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredIPAllocationInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredIPAllocationInformer constructs a new informer for IPAllocation type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredIPAllocationInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.LoadbalancingV1alpha1().IPAllocations(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.LoadbalancingV1alpha1().IPAllocations(namespace).Watch(options)
			},
		},
		&loadbalancingv1alpha1.IPAllocation{},
		resyncPeriod,
		indexers,
	)
}

func (f *iPAllocationInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredIPAllocationInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *iPAllocationInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&loadbalancingv1alpha1.IPAllocation{}, f.defaultInformer)
}

func (f *iPAllocationInformer) Lister() v1alpha1.IPAllocationLister {
	return v1alpha1.NewIPAllocationLister(f.Informer().GetIndexer())
}
