/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "plenus.io/plenuslb/pkg/apis/loadbalancing/v1alpha1"
	scheme "plenus.io/plenuslb/pkg/client/clientset/versioned/scheme"
)

// EphemeralIPPoolsGetter has a method to return a EphemeralIPPoolInterface.
// A group's client should implement this interface.
type EphemeralIPPoolsGetter interface {
	EphemeralIPPools() EphemeralIPPoolInterface
}

// EphemeralIPPoolInterface has methods to work with EphemeralIPPool resources.
type EphemeralIPPoolInterface interface {
	Create(*v1alpha1.EphemeralIPPool) (*v1alpha1.EphemeralIPPool, error)
	Update(*v1alpha1.EphemeralIPPool) (*v1alpha1.EphemeralIPPool, error)
	UpdateStatus(*v1alpha1.EphemeralIPPool) (*v1alpha1.EphemeralIPPool, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.EphemeralIPPool, error)
	List(opts v1.ListOptions) (*v1alpha1.EphemeralIPPoolList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.EphemeralIPPool, err error)
	EphemeralIPPoolExpansion
}

// ephemeralIPPools implements EphemeralIPPoolInterface
type ephemeralIPPools struct {
	client rest.Interface
}

// newEphemeralIPPools returns a EphemeralIPPools
func newEphemeralIPPools(c *LoadbalancingV1alpha1Client) *ephemeralIPPools {
	return &ephemeralIPPools{
		client: c.RESTClient(),
	}
}

// Get takes name of the ephemeralIPPool, and returns the corresponding ephemeralIPPool object, and an error if there is any.
func (c *ephemeralIPPools) Get(name string, options v1.GetOptions) (result *v1alpha1.EphemeralIPPool, err error) {
	result = &v1alpha1.EphemeralIPPool{}
	err = c.client.Get().
		Resource("ephemeralippools").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of EphemeralIPPools that match those selectors.
func (c *ephemeralIPPools) List(opts v1.ListOptions) (result *v1alpha1.EphemeralIPPoolList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.EphemeralIPPoolList{}
	err = c.client.Get().
		Resource("ephemeralippools").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested ephemeralIPPools.
func (c *ephemeralIPPools) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("ephemeralippools").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a ephemeralIPPool and creates it.  Returns the server's representation of the ephemeralIPPool, and an error, if there is any.
func (c *ephemeralIPPools) Create(ephemeralIPPool *v1alpha1.EphemeralIPPool) (result *v1alpha1.EphemeralIPPool, err error) {
	result = &v1alpha1.EphemeralIPPool{}
	err = c.client.Post().
		Resource("ephemeralippools").
		Body(ephemeralIPPool).
		Do().
		Into(result)
	return
}

// Update takes the representation of a ephemeralIPPool and updates it. Returns the server's representation of the ephemeralIPPool, and an error, if there is any.
func (c *ephemeralIPPools) Update(ephemeralIPPool *v1alpha1.EphemeralIPPool) (result *v1alpha1.EphemeralIPPool, err error) {
	result = &v1alpha1.EphemeralIPPool{}
	err = c.client.Put().
		Resource("ephemeralippools").
		Name(ephemeralIPPool.Name).
		Body(ephemeralIPPool).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *ephemeralIPPools) UpdateStatus(ephemeralIPPool *v1alpha1.EphemeralIPPool) (result *v1alpha1.EphemeralIPPool, err error) {
	result = &v1alpha1.EphemeralIPPool{}
	err = c.client.Put().
		Resource("ephemeralippools").
		Name(ephemeralIPPool.Name).
		SubResource("status").
		Body(ephemeralIPPool).
		Do().
		Into(result)
	return
}

// Delete takes name of the ephemeralIPPool and deletes it. Returns an error if one occurs.
func (c *ephemeralIPPools) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("ephemeralippools").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *ephemeralIPPools) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("ephemeralippools").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched ephemeralIPPool.
func (c *ephemeralIPPools) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.EphemeralIPPool, err error) {
	result = &v1alpha1.EphemeralIPPool{}
	err = c.client.Patch(pt).
		Resource("ephemeralippools").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
