/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "plenus.io/plenuslb/pkg/apis/loadbalancing/v1alpha1"
	scheme "plenus.io/plenuslb/pkg/client/clientset/versioned/scheme"
)

// IPAllocationsGetter has a method to return a IPAllocationInterface.
// A group's client should implement this interface.
type IPAllocationsGetter interface {
	IPAllocations(namespace string) IPAllocationInterface
}

// IPAllocationInterface has methods to work with IPAllocation resources.
type IPAllocationInterface interface {
	Create(*v1alpha1.IPAllocation) (*v1alpha1.IPAllocation, error)
	Update(*v1alpha1.IPAllocation) (*v1alpha1.IPAllocation, error)
	UpdateStatus(*v1alpha1.IPAllocation) (*v1alpha1.IPAllocation, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.IPAllocation, error)
	List(opts v1.ListOptions) (*v1alpha1.IPAllocationList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.IPAllocation, err error)
	IPAllocationExpansion
}

// iPAllocations implements IPAllocationInterface
type iPAllocations struct {
	client rest.Interface
	ns     string
}

// newIPAllocations returns a IPAllocations
func newIPAllocations(c *LoadbalancingV1alpha1Client, namespace string) *iPAllocations {
	return &iPAllocations{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the iPAllocation, and returns the corresponding iPAllocation object, and an error if there is any.
func (c *iPAllocations) Get(name string, options v1.GetOptions) (result *v1alpha1.IPAllocation, err error) {
	result = &v1alpha1.IPAllocation{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("ipallocations").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of IPAllocations that match those selectors.
func (c *iPAllocations) List(opts v1.ListOptions) (result *v1alpha1.IPAllocationList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.IPAllocationList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("ipallocations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested iPAllocations.
func (c *iPAllocations) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("ipallocations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a iPAllocation and creates it.  Returns the server's representation of the iPAllocation, and an error, if there is any.
func (c *iPAllocations) Create(iPAllocation *v1alpha1.IPAllocation) (result *v1alpha1.IPAllocation, err error) {
	result = &v1alpha1.IPAllocation{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("ipallocations").
		Body(iPAllocation).
		Do().
		Into(result)
	return
}

// Update takes the representation of a iPAllocation and updates it. Returns the server's representation of the iPAllocation, and an error, if there is any.
func (c *iPAllocations) Update(iPAllocation *v1alpha1.IPAllocation) (result *v1alpha1.IPAllocation, err error) {
	result = &v1alpha1.IPAllocation{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("ipallocations").
		Name(iPAllocation.Name).
		Body(iPAllocation).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *iPAllocations) UpdateStatus(iPAllocation *v1alpha1.IPAllocation) (result *v1alpha1.IPAllocation, err error) {
	result = &v1alpha1.IPAllocation{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("ipallocations").
		Name(iPAllocation.Name).
		SubResource("status").
		Body(iPAllocation).
		Do().
		Into(result)
	return
}

// Delete takes name of the iPAllocation and deletes it. Returns an error if one occurs.
func (c *iPAllocations) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("ipallocations").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *iPAllocations) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("ipallocations").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched iPAllocation.
func (c *iPAllocations) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.IPAllocation, err error) {
	result = &v1alpha1.IPAllocation{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("ipallocations").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
