/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "plenus.io/plenuslb/pkg/apis/loadbalancing/v1alpha1"
	scheme "plenus.io/plenuslb/pkg/client/clientset/versioned/scheme"
)

// PersistentIPPoolsGetter has a method to return a PersistentIPPoolInterface.
// A group's client should implement this interface.
type PersistentIPPoolsGetter interface {
	PersistentIPPools() PersistentIPPoolInterface
}

// PersistentIPPoolInterface has methods to work with PersistentIPPool resources.
type PersistentIPPoolInterface interface {
	Create(*v1alpha1.PersistentIPPool) (*v1alpha1.PersistentIPPool, error)
	Update(*v1alpha1.PersistentIPPool) (*v1alpha1.PersistentIPPool, error)
	UpdateStatus(*v1alpha1.PersistentIPPool) (*v1alpha1.PersistentIPPool, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.PersistentIPPool, error)
	List(opts v1.ListOptions) (*v1alpha1.PersistentIPPoolList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.PersistentIPPool, err error)
	PersistentIPPoolExpansion
}

// persistentIPPools implements PersistentIPPoolInterface
type persistentIPPools struct {
	client rest.Interface
}

// newPersistentIPPools returns a PersistentIPPools
func newPersistentIPPools(c *LoadbalancingV1alpha1Client) *persistentIPPools {
	return &persistentIPPools{
		client: c.RESTClient(),
	}
}

// Get takes name of the persistentIPPool, and returns the corresponding persistentIPPool object, and an error if there is any.
func (c *persistentIPPools) Get(name string, options v1.GetOptions) (result *v1alpha1.PersistentIPPool, err error) {
	result = &v1alpha1.PersistentIPPool{}
	err = c.client.Get().
		Resource("persistentippools").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of PersistentIPPools that match those selectors.
func (c *persistentIPPools) List(opts v1.ListOptions) (result *v1alpha1.PersistentIPPoolList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.PersistentIPPoolList{}
	err = c.client.Get().
		Resource("persistentippools").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested persistentIPPools.
func (c *persistentIPPools) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("persistentippools").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a persistentIPPool and creates it.  Returns the server's representation of the persistentIPPool, and an error, if there is any.
func (c *persistentIPPools) Create(persistentIPPool *v1alpha1.PersistentIPPool) (result *v1alpha1.PersistentIPPool, err error) {
	result = &v1alpha1.PersistentIPPool{}
	err = c.client.Post().
		Resource("persistentippools").
		Body(persistentIPPool).
		Do().
		Into(result)
	return
}

// Update takes the representation of a persistentIPPool and updates it. Returns the server's representation of the persistentIPPool, and an error, if there is any.
func (c *persistentIPPools) Update(persistentIPPool *v1alpha1.PersistentIPPool) (result *v1alpha1.PersistentIPPool, err error) {
	result = &v1alpha1.PersistentIPPool{}
	err = c.client.Put().
		Resource("persistentippools").
		Name(persistentIPPool.Name).
		Body(persistentIPPool).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *persistentIPPools) UpdateStatus(persistentIPPool *v1alpha1.PersistentIPPool) (result *v1alpha1.PersistentIPPool, err error) {
	result = &v1alpha1.PersistentIPPool{}
	err = c.client.Put().
		Resource("persistentippools").
		Name(persistentIPPool.Name).
		SubResource("status").
		Body(persistentIPPool).
		Do().
		Into(result)
	return
}

// Delete takes name of the persistentIPPool and deletes it. Returns an error if one occurs.
func (c *persistentIPPools) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("persistentippools").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *persistentIPPools) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("persistentippools").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched persistentIPPool.
func (c *persistentIPPools) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.PersistentIPPool, err error) {
	result = &v1alpha1.PersistentIPPool{}
	err = c.client.Patch(pt).
		Resource("persistentippools").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
